version: "3.7"

services:
  redis:
    image: redis:alpine
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile
    container_name: api
    restart: always
    ports:
      - "9000:9000"
    environment:
      HOST: 0.0.0.0
      PORT: 9000
      REDIS_HOST: redis
      REDIS_PORT: 6379
      DATABASE_TYPE: postgres
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_DATABASE: postgres
  socket:
    build:
      context: .
      dockerfile: ./apps/socket/Dockerfile
    container_name: socket
    restart: always
    ports:
      - "9100:9100"
    environment:
      PORT: 9100
      REDIS_HOST: redis
      REDIS_PORT: 6379
  client:
    build:
      context: .
      dockerfile: ./apps/client/Dockerfile
    container_name: client
    restart: always
    ports:
      - "8080:80"
    environment:
      VITE_API_URL: http://localhost:9000
      VITE_SOCKET_URL: http://localhost:9100
  admin:
    build:
      context: .
      dockerfile: ./apps/admin/Dockerfile
    container_name: admin
    restart: always
    ports:
      - "8081:80"
    environment:
      VITE_API_URL: http://localhost:9000

volumes:
  redis-data:
    driver: local
  postgres-data:
    driver: local
